Update handler.py.jinja (fixes #1)
mkdocstrings/handler-template pull request #3
Opened 2023-01-10 16:08 UTC by weaversam8

Fixes #1.

2023-01-10 19:45 UTC, pawamoy requested changes
Nice, thanks!

2023-01-10 19:45 UTC, pawamoy commented on project/src/mkdocstrings_handlers/{{python_package_import_name}}/handler.py.jinja
> +    """The {{ llanguage.title().replace(" ", "") }} handler class.
Extraneous `l`!

2023-01-18 19:10 UTC, weaversam8 commented on project/src/mkdocstrings_handlers/{{python_package_import_name}}/handler.py.jinja
> +    """The {{ llanguage.title().replace(" ", "") }} handler class.
Good catch, thanks!

2023-01-18 21:32 UTC, pawamoy approved these changes
Looking good, thanks a lot!

2023-01-18 23:26 UTC, pawamoy commented
I'm gonna fix CI for the template, don't worry about it.

2023-01-23 22:38 UTC, merged